version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tradingview-binance-db
    restart: always
  ts-node-docker:
    build:
      target: production
    environment:
      MYSQL_DATABASE: tradingview-binance-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    command: node build/index.js
