version: '3.7'

services:
  mariadb:
    image: mariadb:10.9.3
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: tradingview-binance-db
    volumes:
      - maria-data:/data/db
      - ./db_init:/docker-entrypoint-initdb.d
    expose:
      - '3306'
    ports:
      - '3306:3306'
    restart: always
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      DB_NAME: tradingview-binance-db
      DB_USER: root
      DB_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      DB_HOST: mariadb
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - '3000'
    ports:
      - '3000:3000'
    restart: on-failure
    command: npm run dev
volumes:
  maria-data:
    driver: local
